// Code generated by templ - DO NOT EDIT.

// templ: version: v0.2.793
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func About() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString("<div class=\"container flex flex-col gap-4 mx-auto\"><h1 class=\"text-4xl font-bold\">about</h1><p>Hey there 👋. My name is Raf, and I'm the creator of Metal. Metal is born out of my experience as Co-founder and CTO at <a href=\"https://www.clever.com\" target=\"_blank\" class=\"link\">Clever</a>. At Clever I spent most of my time building out our internal tools and infrastructure, enabling our relatively small engineering team to serve 10s of millions of students and teachers. I left Clever in 2023 and ever since have missed the tools that we built to deploy and monitor applications. Metal is my attempt to build those tools again, with a focus on simplicity and flexibility.</p><p>If you like what we're doing, I invite you to check us out on <a href=\"https://github.com/onmetal-dev/metal\" target=\"_blank\" class=\"link\">github</a>, join the <a href=\"/\" class=\"link\">waitlist</a>, or reach out to me directly at <a href=\"mailto:raf@onmetal.dev\" class=\"link\">raf@onmetal.dev</a>.</p></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return templ_7745c5c3_Err
	})
}

var _ = templruntime.GeneratedTemplate
