# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json
name: external-dns-cloudflare
shortDescription: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
longDescription: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
iconUrl: https://avatars.githubusercontent.com/u/36015203
defaultNamespace: external-dns
helm:
  chartName: external-dns
  chartVersion: 1.15.0
  repositoryUrl: https://kubernetes-sigs.github.io/external-dns/
  values:
    provider:
      name: cloudflare
    env:
      - name: CF_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: api-token
references:
  - label: Docs
    url: https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/cloudflare.md
  - label: GitHub
    url: https://github.com/kubernetes-sigs/external-dns
