root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
args_bin = []
bin = "./bin/app"
cmd = "make tailwind-build-dev && templ generate && go build -o ./bin/app ./cmd/app"
delay = 1000
exclude_dir = [
    "assets",
    "tmp",
    "vendor",
    "testdata",
    "node_modules",
    "lib/cli",
    "bin",
]
exclude_file = []
exclude_regex = ["_test.go", "_templ.go", "oapi.go"]
exclude_unchanged = false
follow_symlink = false
full_bin = ""
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ"]
include_file = ["./env/local/app/.env"]
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
post_cmd = ["kill -15 $(lsof -ti:8080)"]
pre_cmd = []
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
silent = false
time = false

[misc]
clean_on_exit = false

[proxy]
app_port = 0
enabled = false
proxy_port = 0

[screen]
clear_on_rebuild = false
keep_scroll = true
