root = "."
testdata_dir = "testdata"
tmp_dir = "tmp"

[build]
full_bin = ""
args_bin = []
bin = "./bin/app"
cmd = "make build"
delay = 0
exclude_dir = ["assets", "tmp", "vendor", "testdata", "node_modules", "lib/cli"]
exclude_file = []
exclude_regex = ["_test.go", ".*_templ.go"]
exclude_unchanged = false
follow_symlink = false
include_dir = []
include_ext = ["go", "tpl", "tmpl", "templ", "html", "js"]
include_file = ["./cmd/app/tailwind.config.js", "./env/local/app/.env"]
kill_delay = "0s"
log = "build-errors.log"
poll = false
poll_interval = 0
rerun = false
rerun_delay = 500
send_interrupt = false
stop_on_error = false
post_cmd = ["kill -15 $(lsof -ti:8080)"]

[color]
app = ""
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
main_only = false
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false
keep_scroll = true
