# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json
name: rook-ceph
shortDescription: File, Block, and Object Storage Services for your Cloud-Native Environment
longDescription: A Helm chart for rook-ceph
iconUrl: https://avatars.githubusercontent.com/u/22860722
defaultNamespace: rook-ceph
helm:
  chartName: rook-ceph
  chartVersion: 1.15.2
  repositoryUrl: https://charts.rook.io/release
  values: {}
references:
  - label: GitHub
    url: https://github.com/rook/rook/tree/master/deploy/charts/rook-ceph
