extends:
  - eslint:recommended
  - next/core-web-vitals

rules:
  comma-dangle:
    - error
    - always-multiline
  quotes:
    - error
    - double
    - allowTemplateLiterals: true
  # TypeScript handles this. Details: https://eslint.org/docs/latest/rules/no-undef#handled_by_typescript
  no-undef: "off"
