name: Deploy website from PR

on:
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/next

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '>=20'
          cache: 'npm'

      # - name: Use Bun
      #   uses: oven-sh/setup-bun@v1
      #   with:
      #     bun-version: 1.1.3

      - name: Install packages
        run: npm install

      - name: Install Railway
        run: npm install -g @railway/cli

      - name: Check working directory
        run: pwd && ls && echo "check railway" && railway --help && echo "check npm" && npm --help

      - name: Deploy
        run: railway up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PR }}
