name: Deploy worker to prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.3

      - name: Install packages
        run: bun install --frozen-lockfile

      #   - name: Run tests
      #     run: bun test

      - name: Deploy
        run: bunx @railway/cli up --ci --service worker --environment prod
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
