name: Deploy website to prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/next
    env:
      NODE_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '>=20'

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.3

      - name: Install packages
        run: bun install --frozen-lockfile

      - name: Deploy
        run: bash <(curl -fsSL cli.new) && railway up --ci --service nextjs-service
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
