name: Deploy webapp to prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    env:
      # logic for figuring out which schema in pg to use depends on NODE_ENV
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.3

      - name: Install packages
        run: bun install --frozen-lockfile

      - name: Run tests
        run: bun test

      - name: Push DB changes
        working-directory: ./packages/webapp
        run: bun run db:push
        env:
          NODE_TLS_REJECT_UNAUTHORIZED: "0"
          POSTGRES_URL: ${{ secrets.POSTGRES_URL_PROD }}

      - name: Install Railway cli
        run: |
          wget https://github.com/railwayapp/cli/releases/download/v3.11.0/railway-v3.11.0-amd64.deb
          sudo dpkg -i railway-v3.11.0-amd64.deb

      - name: Deploy
        run: railway up --ci --service webapp --environment prod
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
