name: Deploy website to prod

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/next
    env:
      NODE_ENV: production
      NEXT_TELEMETRY_DISABLED: 1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"

      - name: Use Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.1.3

      - name: Install packages
        run: bun install --frozen-lockfile

      - name: Push DB changes
        run: bun run db:push
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL_PROD }}

      - name: Deploy
        run: |
          bash <(curl -fsSL cli.new) && \
          bunx concurrently "railway up --ci --service website" "railway up --ci --service worker"
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
