name: build-test-deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "log in to GitHub Container Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}

      - name: "build image"
        run: |
          docker build . -f env/prod/app/Dockerfile --tag ghcr.io/onmetal-dev/metal:${{github.sha}}
          docker push ghcr.io/onmetal-dev/metal:${{github.sha}}

  test-go:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: quay.io/tembo/pg16-pgmq:latest
        options: >-
          --health-cmd="pg_isready"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5433:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: metal_test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: make install_deps

      - name: Test
        run: make test-go

  test-vet-staticcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: make install_deps

      - name: vet and staticcheck
        run: make test-vet test-staticcheck

  deploy:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [test-vet-staticcheck, test-go, build]
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway cli
        run: |
          wget https://github.com/railwayapp/cli/releases/download/v3.12.2/railway-v3.12.2-amd64.deb
          sudo dpkg -i railway-v3.12.2-amd64.deb

      - name: Deploy
        run: railway up --ci --service app --environment production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN_PROD }}
