name: Build and Release

on:
  push
  # push:
  #   tags:
  #     - 'v*'
  # push:
  #   branches:
  #     - main  # Change this to the branch you want to trigger the action

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./apps/cli

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ">=20"

      - name: Use Bun
        uses: oven-sh/setup-bun@v1

      - name: Install packages
        run: bun install --frozen-lockfile

      - name: Create Release file
        run: |
          echo "Version: ${{ github.ref_name }}" > Release.txt
          echo "Commit: ${{ github.sha }}"" >> Release.txt

      - name: Test Release file
        run: cat Release.txt

      - name: Build executables to release
        run: |
          bun build --compile --target=bun-darwin-x64 --outfile metal-${{ github.ref_name }}-darwin-x64 src/index.ts
          bun build --compile --target=bun-darwin-arm64 --outfile metal-${{ github.ref_name }}-darwin-arm64 src/index.ts
          bun build --compile --target=bun-linux-arm64 --outfile metal-${{ github.ref_name }}-linux-arm64 src/index.ts
          bun build --compile --target=bun-linux-x64 --outfile metal-${{ github.ref_name }}-linux-x64 src/index.ts
          bun build --compile --target=bun-windows-x64 --outfile metal-${{ github.ref_name }}-windows-x64 src/index.ts

      - name: List files and pwd
        run: |
          ls -l
          pwd

      - name: Compress the executables
        run: |
          tar -czvf metal-${{ github.ref_name }}-darwin-arm64.tar.gz metal-${{ github.ref_name }}-darwin-arm64
          tar -czvf metal-${{ github.ref_name }}-darwin-x64.tar.gz metal-${{ github.ref_name }}-darwin-x64
          tar -czvf metal-${{ github.ref_name }}-linux-arm64.tar.gz metal-${{ github.ref_name }}-linux-arm64
          tar -czvf metal-${{ github.ref_name }}-linux-x64.tar.gz metal-${{ github.ref_name }}-linux-x64
          tar -czvf metal-${{ github.ref_name }}-windows-x64.tar.gz metal-${{ github.ref_name }}-windows-x64

      - name: Save binaries' hashes
        run: |
          echo "Hashes of binaries:" >> Release.txt
          sha256sum metal-*.tar.gz >> Release.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./apps/cli/metal-*.tar.gz
            ./apps/cli/Release.txt
            LICENSE
